# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coster', '0002_auto_20170607_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
