# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coster', '0005_rides'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='category',
            field=models.CharField(default='s', max_length=1),
        ),
    ]
