# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coster', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='calls',
        ),
        migrations.RemoveField(
            model_name='client',
            name='paid',
        ),
        migrations.AddField(
            model_name='client',
            name='description',
            field=models.TextField(default=None, max_length=200),
        ),
    ]
