# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coster', '0003_auto_20170607_0732'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rides',
        ),
    ]
