# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coster', '0004_delete_rides'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('danger_rate', models.FloatField()),
                ('danger', models.CharField(max_length=100)),
                ('age_limit', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
